### ISSUE TITLE
Error in file exists

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/tinyviztest#1]
Hey Vincent,

I'm finally getting a chance to try this out for one of my own packages. 

Unfortunately, I'm running into a bit of a roadblock with the tests that I've written [here](https://github.com/grantmcdermott/ggiplot/blob/dev/inst/tinytest/test_ggiplot.R). Specifically:

```
library(tintytest)
test_all()                                                                                                                                                                  
test_ggiplot.R................    0 tests    Error in if (!file.exists(fn_target) || isTRUE(overwrite)) { : 
  missing value where TRUE/FALSE needed
```

Running the tests manually, I encounter this error for the very first test (line 40). 

Am I just doing something daft?

**Comment by grantmcdermott** [comment]
PS. I cloned and and ran the tests in this repo (i.e. `tinyviztest` itself). These run at least, but I'm still encountering some errors. Specifically, the tests are failing even on the 2nd run, since it doesn't look like the first run is correctly writing the plot(s) to file. 

```r
## Note: now in the cloned tinyviztest repo

> library("tinytest")
> using("tinyviztest")
> p1 <- function() plot(mtcars$hp, mtcars$mpg)
> # 1st run fails but writes the target to file
> expect_vdiff(p1, "base simple")
----- FAILED[]: <-->
 call| expect_vdiff(p1, "base simple")
 diff| 0
 info| new plot was saved to: _tinyviztest/base_simple-001.png 
Warning message:
In file.rename(fn_current, fn_target) :
  cannot rename file '/tmp/RtmpJyv3mf/file7423486c7e20/current/base_simple-001.png' to '_tinyviztest/base_simple-001.png', reason 'Invalid cross-device link'
> # 2nd run succeeds
> expect_vdiff(p1, "base simple")
----- FAILED[]: <-->
 call| expect_vdiff(p1, "base simple")
 diff| 0
 info| new plot was saved to: _tinyviztest/base_simple-001.png 
Warning message:
In file.rename(fn_current, fn_target) :
  cannot rename file '/tmp/RtmpJyv3mf/file742352ddc6b6/current/base_simple-001.png' to '_tinyviztest/base_simple-001.png', reason 'Invalid cross-device link'

# Check that nothing has been written to disk
> list.files("inst/tinytest/_tinyviztest/")
character(0)
```

**Comment by vincentarelbundock** [comment]
Tried to google this error but didn't find much except some talk about encrypted volumes. I get the same error, so maybe WSL?

In any case, I just pushed a commit that uses the `fs` package to copy instead of base R, and it seems to now copy the reference file correctly.

**Comment by vincentarelbundock** [comment]
FYI @grantmcdermott , the `tinytest` dev merged my patch and I re-wrote the whole `tinyviztest` package. I think that if you install both dev versions, everything should work now.

I've also re-written the README with a much more detailed tutorial.

Closing this issue now, but don't hesitate to open a new one if needed.

**Comment by grantmcdermott** [comment]
Brilliant, thanks mate! I'll update to the dev versions and get re-run the infrastructure on my ggiplot package before getting it out to CRAN. Much appreciated.
