### ISSUE TITLE
R CMD check for CRAN / CI workflows 

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/tinyviztest#5]
That's a lot of acronyms in the header, but hopefully clear enough. I'm wondering how to operationalise the sandboxed R CMD checks for CRAN or GitHub Actions CI, given that tinyviztest has to complete a failed run first. For the latter I can imagine including a hook that runs `tinytest::run_test_dir()` after the dependency setup step here. https://github.com/grantmcdermott/ggiplot/actions/runs/3808182939/jobs/6478543915#step:19:281 This should generate all the reference plots required for a passing second run (i.e., through R CMD check).

But I'm not sure how this would work with CRAN's testing infrastructure. 

Am I just missing something obvious?

Otherwise, loving the package functionality. Thanks!

**Comment by vincentarelbundock** [comment]
Normally we want snapshots to be definitively "fixed" to a known version. So you would just run `tinytest` locally to generate the snapshots, commit them to git, and then everything should work as normal. 

What am I missing?

**Comment by vincentarelbundock** [comment]
@grantmcdermott I opened a PR on your repo to show what I think needed to be done.: https://github.com/grantmcdermott/ggiplot/pull/14

**Comment by grantmcdermott** [comment]
Brilliant. Thanks V. Let me merge over there.
