### ISSUE TITLE
Unexpected Behavior with Multiple `using()` calls

### ISSUE THREAD

**Issue by barbehenna** [vincentarelbundock/tinyviztest#9]
I've been playing around with this package for a course I'm working on and really love it, but I keep running into an odd error that I am tracing to the `using("tinyviztest")` call. The problem (to my eyes) is coming from the `using()` mechanism, which I'm not familiar with, so I'm at a bit of a loss debugging beyond this point. This package is really awesome when it works, and I would be happy to help debug or fix this problem if you can provide direction. 

My set up is as follows:

- I'm working in a docker image (eddelbuettel/r2u:22.04) with `tinytest`, `ragg`, `magick`, `checkmate`, `Rcpp`, `diffobj`, and `crayon` installed from CRAN (`tinytest` is at 1.3.1 on CRAN now), and `tinyviztest` install from GitHub with `remotes`; 
- I placed two copies of the base R demo test file (https://github.com/vincentarelbundock/tinyviztest#base-r-graphics) at `/tests/test_0.R` and `/tests/test_1.R`.

When I run `tinytest::run_test_dir("/tests")` I see the following behavior:

```r
> tinytest::run_test_dir("/tests")
test_0.R......................    2 tests 2 fails 2.0s
test_1.R......................    0 tests    Error in ext[[pkg]] : subscript out of bounds
> traceback()
6: using("tinyviztest")
5: eval(expr, envir = e)
4: eval(expr, envir = e)
3: FUN(X[[i]], ...)
2: lapply(basename(testfiles), run_test_file, at_home = at_home, 
       verbose = verbose, color = color, remove_side_effects = remove_side_effects, 
       ...)
1: tinytest::run_test_dir("/tests")
```

Furthermore, if I delete the `test_1.R` file, it again looks like it works on the first run but breaks on the second.

```r
> tinytest::run_test_dir("/tests")
test_0.R......................    2 tests 2 fails 2.0s
----- FAILED[]: test_0.R<9--9>
 call| expect_snapshot_plot(p1, label = "base_example")

 info| Creating snapshot: _tinyviztest/base_example.png
 ----- FAILED[]: test_0.R<12--12>
 call| expect_snapshot_plot(p2, label = "base_example")
 diff| 3274
 info| Diff plot saved to: _tinyviztest_review/base_example.png
 
> tinytest::run_test_dir("/tests")
test_0.R......................    0 tests    Error in ext[[pkg]] : subscript out of bounds
> traceback()
6: using("tinyviztest")
5: eval(expr, envir = e)
4: eval(expr, envir = e)
3: FUN(X[[i]], ...)
2: lapply(basename(testfiles), run_test_file, at_home = at_home, 
       verbose = verbose, color = color, remove_side_effects = remove_side_effects, 
       ...)
1: tinytest::run_test_dir("/tests")
```

Finally, if I perform this second test where I restart the R session between calls to `tinytest::run_test_dir()` the second test works as expected.

**Comment by vincentarelbundock** [comment]
Glad to hear you think this is useful!

Can you try to install the dev version of `tinytest`? @markvanderloo recently merged a patch to fix an issue that looked a lot like this one: `tinyviztest` and `checkmate` were both trying to register new tests, and this raised a `Error in ext[[pkg]]`.

```{r}
library(remotes)
install_github("markvanderloo/tinytest/pkg")
```

Note that `pkg` at the end of that Github link.

**Comment by barbehenna** [comment]
I think that fixed it! Using the dev version of `tinytest` (1.4.0) the errors I traced to `using()` disappear. I guess I will use the dev version  of `tinytest` until it hits CRAN.

**Comment by vincentarelbundock** [comment]
Great!

Please be aware that I'm still treating this package as experimental. I may even change the name before releasing to CRAN.

**Comment by barbehenna** [comment]
Thanks for the heads up (and help)! I'll keep that in mind as I work with it.

**Comment by eddelbuettel** [comment]
Wicked!!  @markvanderloo  and I actually had a back-and-forth today regarding 1.4.0 and a needed follow-up from `ttdo`.  Looks like all will be good for all 'Real Soon Now'.   So who do I send the virtual beer to for the `using` issue?  I have a vague recollection @vincentarelbundock told me about it ages ago...

**Comment by vincentarelbundock** [comment]
Yeah, not much credit needed, as it was just 2 lines of code. But "virtual beers" are quite cheap, I gather.

**Comment by vincentarelbundock** [comment]
@barbehenna FYI, the package is now `tinysnapshot`. The rest has not changed, so you should just be able to search and replace the very distinctive `tinyviztest` string, and things should work as before.

**Comment by barbehenna** [comment]
Thank you for the heads up!
